; M5Stack StopWatch (SKU: C152 / ESP32-S3R8, 16MB Flash + 8MB PSRAM)
[env:stopwatch]
platform = espressif32 @ 6.12.0
board = esp32s3box
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

lib_deps =
	m5stack/M5Unified @ ^0.2.7
	bblanchon/ArduinoJson @ ^7.2.0
